# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

title: Thomas Stringer                          # the main title

tagline: Software Engineer  # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  Blog and portfolio focused on
  Linux, Kubernetes, containers, DevOps,
  Azure, and other technical things.

# Replace with the website url, e.g. 'https://username.github.io'
url: 'https://trstringer.com'

author: Thomas Stringer                  # change to your full name

avatar: /images/Logo-C.png   # support internet resources

plugins:
  - jekyll-analytics

github:
  username: trstringer             # change to your github username

twitter:
  username: tr_stringer            # change to your twitter username

social:
  name: Thomas Stringer                  # it will shows as the copyright owner in Footer
  email: thomas@trstringer.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/tr_stringer      # change to your twitter homepage
    - https://github.com/trstringer       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/trstringer

google_site_verification: google_meta_tag_verification # change to your verification string

#--------------------------

# if your site type is Project Pages site, change below value to '/projectname'
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

jekyll_analytics:
  Plausible:
    domain: 'trstringer.com'   # The domain configured in plausible
    source: 'https://plausible.io/js/plausible.js' # The source of the javascript

# google_analytics:
#   # Fill with your Google Analytics ID
#   id: 'UA-157846596-1'
#   # The Google Analytics pageviews switch.
# 
#   pv:
#     # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
#     enabled: false
#     # the next options only valid when `google_analytics.pv` is enabled.
#     proxy_url: ''
#     proxy_endpoint: ''
#     cache: false  # pv data local cache, good for the users from GFW area.

disqus:
  comments: false  # boolean type, the global switch for posts comments.
  shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: light

# boolean type, global switch for ToC in posts.
toc: true

paginate: 10

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /:title/

defaults:
  -
    scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: tags
    values:
      tab_active: Tags
      location: Tag
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      tab_active: Categories
      location: Category
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      layout: page
      dynamic_title: true    # Hide title in mobile screens.
      breadcrumb:
        -
          label: Home
          url: /
  -
    scope:
      path: assets/data
    values:
      layout: compress


sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp,
            optgroup, option, colgroup, caption,
            thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor        # Avoid Jekyll mistakenly read the vender directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md

sitemap_exclude:  # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
