name: build
on:
  push:
    branches-ignore:
      - stable
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - '.travis.yml'
      - '.gitignore'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths:
      - "**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: '2.6.10'
          ruby-version: '3.0'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bundle Caching
        id: bundle-cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install GNU-Coreutils(for macOS)
        if: runner.os == 'macOS'
        run: |
          brew install coreutils

      - name: Bundle config
        run: |
          bundle config path vendor/bundle

      - name: Bundle Install
        if: steps.bundle-cache.outputs.cache-hit != 'true'
        run: |
          bundle install

      - name: Bundle Install locally
        if: steps.bundle-cache.outputs.cache-hit == 'true'
        run: |
          bundle install --local

      - name: Build Site
        run: |
          bash tools/build.sh

      - name: Test Site
        run: |
          bash tools/test.sh
